[package]
name = "gptextract"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["socks", "rustls-tls", "json"] }
select = "0.6.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }